config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  root 'home#index'

  namespace :thnk do
    resources :products, only: [:index] do
      collection do
        get :bulk_print
      end
    end

    get 'variants/:uuid/details', to: 'variants#details', as: 'variant_details'
  end
  namespace :scanner do
    get 'camera' => 'camera#index'
    post 'camera/scan' => 'camera#scan'          # Route for scanning QR codes via API
    get 'lookup/:uuid' => 'scanner#lookup', as: 'lookup'  # Route for looking up products by UUID
  end
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/grid_items/_bubble_services.html.erb
<div class="group relative p-6 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-500">
  <div>
    <span class="inline-flex shadow rounded-lg p-1.5 bg-sky-200 ">
      <%= image_tag 'services.svg' , class: "h-10 w-10" %>
    </span>
  </div>
  <div class="mt-8">
    <h3 class=" text-3xl text-sky-700 mb-4 leading-6 leading-6 ">
      <a href="#" class="disable focus:outline-none">
        <!-- Extend touch target to entire panel -->
        <span class="absolute inset-0" aria-hidden="true"></span>
        Bubble Services
      </a>
    </h3>
    <p class="mt-2 text-sm text-gray-500">Doloribus dolores nostrum quia qui natus officia quod et dolorem.
      Sit repellendus qui ut at blanditiis et quo et molestiae.</p>
  </div>
  <span class="pointer-events-none absolute right-6 top-6 text-gray-900 group-hover:text-gray-400" aria-hidden="true">
    <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24">
      <path
        d="M20 4h1a1 1 0 00-1-1v1zm-1 12a1 1 0 102 0h-2zM8 3a1 1 0 000 2V3zM3.293 19.293a1 1 0 101.414 1.414l-1.414-1.414zM19 4v12h2V4h-2zm1-1H8v2h12V3zm-.707.293l-16 16 1.414 1.414 16-16-1.414-1.414z" />
    </svg>
  </span>
</div>

app/views/home/grid_items/_logo_cards.html.erb
<ul role="list" class="grid grid-cols-1 gap-x-6 gap-y-8 lg:grid-cols-3 xl:gap-x-8">
  <li class="overflow-hidden rounded-xl border border-gray-200">
    <div class="flex items-center gap-x-4 border-b border-gray-900/5 bg-gray-50 p-6">
      <img src="https://tailwindui.com/plus/img/logos/48x48/tuple.svg" alt="Tuple"
           class="h-12 w-12 flex-none rounded-lg bg-white object-cover ring-1 ring-gray-900/10">
      <div class="text-sm font-medium leading-6 text-gray-900">Tuple</div>
      <div class="relative ml-auto">
        <button type="button" class="-m-2.5 block p-2.5 text-gray-400 hover:text-gray-500" id="options-menu-0-button"
                aria-expanded="false" aria-haspopup="true">
          <span class="sr-only">Open options</span>
          <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
            <path
              d="M3 10a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0ZM8.5 10a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0ZM15.5 8.5a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3Z" />
          </svg>
        </button>

        <!--
          Dropdown menu, show/hide based on menu state.

          Entering: "transition ease-out duration-100"
            From: "transform opacity-0 scale-95"
            To: "transform opacity-100 scale-100"
          Leaving: "transition ease-in duration-75"
            From: "transform opacity-100 scale-100"
            To: "transform opacity-0 scale-95"
        -->
        <div
          class="absolute right-0 z-10 mt-0.5 w-32 origin-top-right rounded-md bg-white py-2 shadow-lg ring-1 ring-gray-900/5 focus:outline-none"
          role="menu" aria-orientation="vertical" aria-labelledby="options-menu-0-button" tabindex="-1">
          <!-- Active: "bg-gray-50", Not Active: "" -->
          <a href="#" class="block px-3 py-1 text-sm leading-6 text-gray-900" role="menuitem" tabindex="-1"
             id="options-menu-0-item-0">View<span class="sr-only">, Tuple</span></a>
          <a href="#" class="block px-3 py-1 text-sm leading-6 text-gray-900" role="menuitem" tabindex="-1"
             id="options-menu-0-item-1">Edit<span class="sr-only">, Tuple</span></a>
        </div>
      </div>
    </div>
    <dl class="-my-3 divide-y divide-gray-100 px-6 py-4 text-sm leading-6">
      <div class="flex justify-between gap-x-4 py-3">
        <dt class="text-gray-500">Last invoice</dt>
        <dd class="text-gray-700"><time datetime="2022-12-13">December 13, 2022</time></dd>
      </div>
      <div class="flex justify-between gap-x-4 py-3">
        <dt class="text-gray-500">Amount</dt>
        <dd class="flex items-start gap-x-2">
          <div class="font-medium text-gray-900">$2,000.00</div>
          <div
            class="rounded-md bg-red-50 px-2 py-1 text-xs font-medium text-red-700 ring-1 ring-inset ring-red-600/10">
            Overdue</div>
        </dd>
      </div>
    </dl>
  </li>
  <li class="overflow-hidden rounded-xl border border-gray-200">
    <div class="flex items-center gap-x-4 border-b border-gray-900/5 bg-gray-50 p-6">
      <img src="https://tailwindui.com/plus/img/logos/48x48/savvycal.svg" alt="SavvyCal"
           class="h-12 w-12 flex-none rounded-lg bg-white object-cover ring-1 ring-gray-900/10">
      <div class="text-sm font-medium leading-6 text-gray-900">SavvyCal</div>
      <div class="relative ml-auto">
        <button type="button" class="-m-2.5 block p-2.5 text-gray-400 hover:text-gray-500" id="options-menu-1-button"
                aria-expanded="false" aria-haspopup="true">
          <span class="sr-only">Open options</span>
          <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
            <path
              d="M3 10a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0ZM8.5 10a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0ZM15.5 8.5a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3Z" />
          </svg>
        </button>

        <!--
          Dropdown menu, show/hide based on menu state.

          Entering: "transition ease-out duration-100"
            From: "transform opacity-0 scale-95"
            To: "transform opacity-100 scale-100"
          Leaving: "transition ease-in duration-75"
            From: "transform opacity-100 scale-100"
            To: "transform opacity-0 scale-95"
        -->
        <div
          class="absolute right-0 z-10 mt-0.5 w-32 origin-top-right rounded-md bg-white py-2 shadow-lg ring-1 ring-gray-900/5 focus:outline-none"
          role="menu" aria-orientation="vertical" aria-labelledby="options-menu-1-button" tabindex="-1">
          <!-- Active: "bg-gray-50", Not Active: "" -->
          <a href="#" class="block px-3 py-1 text-sm leading-6 text-gray-900" role="menuitem" tabindex="-1"
             id="options-menu-1-item-0">View<span class="sr-only">, SavvyCal</span></a>
          <a href="#" class="block px-3 py-1 text-sm leading-6 text-gray-900" role="menuitem" tabindex="-1"
             id="options-menu-1-item-1">Edit<span class="sr-only">, SavvyCal</span></a>
        </div>
      </div>
    </div>
    <dl class="-my-3 divide-y divide-gray-100 px-6 py-4 text-sm leading-6">
      <div class="flex justify-between gap-x-4 py-3">
        <dt class="text-gray-500">Last invoice</dt>
        <dd class="text-gray-700"><time datetime="2023-01-22">January 22, 2023</time></dd>
      </div>
      <div class="flex justify-between gap-x-4 py-3">
        <dt class="text-gray-500">Amount</dt>
        <dd class="flex items-start gap-x-2">
          <div class="font-medium text-gray-900">$14,000.00</div>
          <div
            class="rounded-md bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">
            Paid</div>
        </dd>
      </div>
    </dl>
  </li>
  <li class="overflow-hidden rounded-xl border border-gray-200">
    <div class="flex items-center gap-x-4 border-b border-gray-900/5 bg-gray-50 p-6">
      <img src="https://tailwindui.com/plus/img/logos/48x48/reform.svg" alt="Reform"
           class="h-12 w-12 flex-none rounded-lg bg-white object-cover ring-1 ring-gray-900/10">
      <div class="text-sm font-medium leading-6 text-gray-900">Reform</div>
      <div class="relative ml-auto">
        <button type="button" class="-m-2.5 block p-2.5 text-gray-400 hover:text-gray-500" id="options-menu-2-button"
                aria-expanded="false" aria-haspopup="true">
          <span class="sr-only">Open options</span>
          <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
            <path
              d="M3 10a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0ZM8.5 10a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0ZM15.5 8.5a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3Z" />
          </svg>
        </button>

        <!--
          Dropdown menu, show/hide based on menu state.

          Entering: "transition ease-out duration-100"
            From: "transform opacity-0 scale-95"
            To: "transform opacity-100 scale-100"
          Leaving: "transition ease-in duration-75"
            From: "transform opacity-100 scale-100"
            To: "transform opacity-0 scale-95"
        -->
        <div
          class="absolute right-0 z-10 mt-0.5 w-32 origin-top-right rounded-md bg-white py-2 shadow-lg ring-1 ring-gray-900/5 focus:outline-none"
          role="menu" aria-orientation="vertical" aria-labelledby="options-menu-2-button" tabindex="-1">
          <!-- Active: "bg-gray-50", Not Active: "" -->
          <a href="#" class="block px-3 py-1 text-sm leading-6 text-gray-900" role="menuitem" tabindex="-1"
             id="options-menu-2-item-0">View<span class="sr-only">, Reform</span></a>
          <a href="#" class="block px-3 py-1 text-sm leading-6 text-gray-900" role="menuitem" tabindex="-1"
             id="options-menu-2-item-1">Edit<span class="sr-only">, Reform</span></a>
        </div>
      </div>
    </div>
    <dl class="-my-3 divide-y divide-gray-100 px-6 py-4 text-sm leading-6">
      <div class="flex justify-between gap-x-4 py-3">
        <dt class="text-gray-500">Last invoice</dt>
        <dd class="text-gray-700"><time datetime="2023-01-23">January 23, 2023</time></dd>
      </div>
      <div class="flex justify-between gap-x-4 py-3">
        <dt class="text-gray-500">Amount</dt>
        <dd class="flex items-start gap-x-2">
          <div class="font-medium text-gray-900">$7,600.00</div>
          <div
            class="rounded-md bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">
            Paid</div>
        </dd>
      </div>
    </dl>
  </li>
</ul>

app/views/home/grid_items/_top_left.html.erb
<div
  class=" bg-transparent group relative rounded-tl-lg rounded-tr-lg  p-6 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-500 sm:rounded-tr-none">
  <div class="">
    <span class="inline-flex rounded-lg bg-teal-100 bg-opacity-70 p-2 text-teal-700 ">
      <svg class="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke-width="1" stroke="currentColor" aria-hidden="true"
           data-slot="icon">
        <path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
      </svg>
    </span>
  </div>
  <div class="mt-8">
    <h3 class=" text-3xl  mb-4 leading-6 text-teal-700">
      <a href="#" class="focus:outline-none">
        <!-- Extend touch target to entire panel -->
        <span class="absolute inset-0 " aria-hidden="true"></span>
        Inventory
      </a>
    </h3>
    <p class="isolate leading-6 text-teal-700">
      <%= link_to 'Inventory', thnk_products_path, class: "text-teal-700 underline" %>
    </p>
    <p class="mt-2 text-md text-gray-900"><span class="text-teal-700 font-semibold">Coming Soon: </span>Manage Inventory
      from one place & across shopify stores.</p>
  </div>
  <span class="pointer-events-none absolute right-6 top-6 text-gray-300 group-hover:text-gray-400" aria-hidden="true">
    <svg class="h-6 w-6 text-slate-600" fill="currentColor" viewBox="0 0 24 24">
      <path
        d="M20 4h1a1 1 0 00-1-1v1zm-1 12a1 1 0 102 0h-2zM8 3a1 1 0 000 2V3zM3.293 19.293a1 1 0 101.414 1.414l-1.414-1.414zM19 4v12h2V4h-2zm1-1H8v2h12V3zm-.707.293l-16 16 1.414 1.414 16-16-1.414-1.414z" />
    </svg>
  </span>
</div>

app/views/home/grid_items/_top_right.html.erb
<div
  class="group relative bg-transparent p-6 hover:ring-black focus-within:ring-2 focus-within:ring-inset focus-within:ring-slate-500 sm:rounded-tr-lg">
  <div>
    <span class="inline-flex rounded-lg shadow p-2 bg-purple-200 bg-opacity-70  ">
      <%= image_tag 'cam1.svg' , class: "h-8 w-8" %>
    </span>
  </div>
  <div class="mt-8">
    <h3 class=" text-3xl leading-6 mb-4 text-purple-700">
      <a href="#" class="focus:outline-none">
        <!-- Extend touch target to entire panel -->
        <span class="absolute inset-0" aria-hidden="true"></span>
        Scanner
      </a>
    </h3>
    <p class="isolate mt-2 text-md text-gray-900">
      Scan
      <%= link_to 'QRCodes', scanner_camera_path, class: "text-purple-700 underline" %>
      , Documents, or
      <%= link_to 'Count Inventory' , '#', class: "text-purple-700 underline" %>
      with bubble.
    </p>
  </div>
  <span class="pointer-events-none absolute right-6 top-6 text-gray-700 group-hover:text-gray-400" aria-hidden="true">
    <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24">
      <path
        d="M20 4h1a1 1 0 00-1-1v1zm-1 12a1 1 0 102 0h-2zM8 3a1 1 0 000 2V3zM3.293 19.293a1 1 0 101.414 1.414l-1.414-1.414zM19 4v12h2V4h-2zm1-1H8v2h12V3zm-.707.293l-16 16 1.414 1.414 16-16-1.414-1.414z" />
    </svg>
  </span>
</div>